PRINT '*********************************************'
PRINT 'Inserción en la tabla Especialidades'
PRINT '*********************************************'

DECLARE	@idUsuario UNIQUEIDENTIFIER

SELECT TOP 1 
	@idUsuario = Id
FROM dbo.Usuarios

INSERT INTO dbo.Especialidades SELECT NEWID(), 'ALERGIA',11,GETDATE(),@idUsuario
INSERT INTO dbo.Especialidades SELECT NEWID(), 'ALERGIA INFANTIL',12,GETDATE(),@idUsuario
INSERT INTO dbo.Especialidades SELECT NEWID(), 'INMUNOLOGIA',13,GETDATE(),@idUsuario
INSERT INTO dbo.Especialidades SELECT NEWID(), 'INMUNOLOGIA INFANTIL',14,GETDATE(),@idUsuario
INSERT INTO dbo.Especialidades SELECT NEWID(), 'ANESTESIOLOGIA',21,GETDATE(),@idUsuario
INSERT INTO dbo.Especialidades SELECT NEWID(), 'CARDIOANGIOLOGIA',31,GETDATE(),@idUsuario
INSERT INTO dbo.Especialidades SELECT NEWID(), 'CARDIOLOGIA',32,GETDATE(),@idUsuario
INSERT INTO dbo.Especialidades SELECT NEWID(), 'CARDIOLOGIA GERIATRICA',33,GETDATE(),@idUsuario
INSERT INTO dbo.Especialidades SELECT NEWID(), 'CARDIOLOGIA PEDIATRICA',34,GETDATE(),@idUsuario
INSERT INTO dbo.Especialidades SELECT NEWID(), 'HEMODINAMIA',35,GETDATE(),@idUsuario
INSERT INTO dbo.Especialidades SELECT NEWID(), 'CIRUGIA CARDIOVASCULAR',41,GETDATE(),@idUsuario
INSERT INTO dbo.Especialidades SELECT NEWID(), 'CIRUGIA DE CABEZA/CUELLO',42,GETDATE(),@idUsuario
INSERT INTO dbo.Especialidades SELECT NEWID(), 'CIRUGIA GASTROENTEROLOG.',43,GETDATE(),@idUsuario
INSERT INTO dbo.Especialidades SELECT NEWID(), 'CIRUGIA GENERAL',44,GETDATE(),@idUsuario
INSERT INTO dbo.Especialidades SELECT NEWID(), 'CIRUGIA INFANTIL',45,GETDATE(),@idUsuario
INSERT INTO dbo.Especialidades SELECT NEWID(), 'CIRUGIA ONCOLOGICA',46,GETDATE(),@idUsuario
INSERT INTO dbo.Especialidades SELECT NEWID(), 'CIRUGIA PLASTICA',47,GETDATE(),@idUsuario
INSERT INTO dbo.Especialidades SELECT NEWID(), 'CIRUGIA PROCTOLOGICA',48,GETDATE(),@idUsuario
INSERT INTO dbo.Especialidades SELECT NEWID(), 'CIRUGIA TORAXICA',49,GETDATE(),@idUsuario
INSERT INTO dbo.Especialidades SELECT NEWID(), 'CIRUGIA VASCULAR',40,GETDATE(),@idUsuario
INSERT INTO dbo.Especialidades SELECT NEWID(), 'CLINICA MEDICA',51,GETDATE(),@idUsuario
INSERT INTO dbo.Especialidades SELECT NEWID(), 'MEDICINA DEL DEPORTE',61,GETDATE(),@idUsuario
INSERT INTO dbo.Especialidades SELECT NEWID(), 'DERMATOLOGIA',71,GETDATE(),@idUsuario
INSERT INTO dbo.Especialidades SELECT NEWID(), 'DERMATOLOGIA INFANTIL',72,GETDATE(),@idUsuario
INSERT INTO dbo.Especialidades SELECT NEWID(), 'ENDOCRINOLOGIA',81,GETDATE(),@idUsuario
INSERT INTO dbo.Especialidades SELECT NEWID(), 'ENDOCRINOLOGIA INFANTIL',82,GETDATE(),@idUsuario
INSERT INTO dbo.Especialidades SELECT NEWID(), 'ENDOCRINOLOGIA/NUTICION',83,GETDATE(),@idUsuario
INSERT INTO dbo.Especialidades SELECT NEWID(), 'ANDROLOGIA Y EST.MASC.',91,GETDATE(),@idUsuario
INSERT INTO dbo.Especialidades SELECT NEWID(), 'ESTERILIDAD FEMENINA',92,GETDATE(),@idUsuario
INSERT INTO dbo.Especialidades SELECT NEWID(), 'REPRODUCCION',93,GETDATE(),@idUsuario
INSERT INTO dbo.Especialidades SELECT NEWID(), 'FLEBOLOGIA',101,GETDATE(),@idUsuario
INSERT INTO dbo.Especialidades SELECT NEWID(), 'LINFOLOGIA',102,GETDATE(),@idUsuario
INSERT INTO dbo.Especialidades SELECT NEWID(), 'GASTROENTEROLOGIA',111,GETDATE(),@idUsuario
INSERT INTO dbo.Especialidades SELECT NEWID(), 'GASTROENTEROLOGIA INFANTIL',112,GETDATE(),@idUsuario
INSERT INTO dbo.Especialidades SELECT NEWID(), 'HEPATOLOGIA',113,GETDATE(),@idUsuario
INSERT INTO dbo.Especialidades SELECT NEWID(), 'GENETICA',121,GETDATE(),@idUsuario
INSERT INTO dbo.Especialidades SELECT NEWID(), 'GERIATRIA Y GERONTOLOGIA',131,GETDATE(),@idUsuario
INSERT INTO dbo.Especialidades SELECT NEWID(), 'GINECOLOGIA',141,GETDATE(),@idUsuario
INSERT INTO dbo.Especialidades SELECT NEWID(), 'GINECOLOGIA INFANTO-JUVENIL',142,GETDATE(),@idUsuario
INSERT INTO dbo.Especialidades SELECT NEWID(), 'OBSTETRICIA',143,GETDATE(),@idUsuario
INSERT INTO dbo.Especialidades SELECT NEWID(), 'TOCOGINECOLOGIA',144,GETDATE(),@idUsuario
INSERT INTO dbo.Especialidades SELECT NEWID(), 'HEMATOLOGIA',151,GETDATE(),@idUsuario
INSERT INTO dbo.Especialidades SELECT NEWID(), 'HEMATOLOGIA INFANTIL',152,GETDATE(),@idUsuario
INSERT INTO dbo.Especialidades SELECT NEWID(), 'HEMATOLOGIA ONCOLOGICA',153,GETDATE(),@idUsuario
INSERT INTO dbo.Especialidades SELECT NEWID(), 'HEMOSTASIA',154,GETDATE(),@idUsuario
INSERT INTO dbo.Especialidades SELECT NEWID(), 'HEMOTERAPIA',155,GETDATE(),@idUsuario
INSERT INTO dbo.Especialidades SELECT NEWID(), 'INFECTOLOGIA',161,GETDATE(),@idUsuario
INSERT INTO dbo.Especialidades SELECT NEWID(), 'INFECTOLOGIA PEDIATRICA',162,GETDATE(),@idUsuario
INSERT INTO dbo.Especialidades SELECT NEWID(), 'PARASITOLOGIA',163,GETDATE(),@idUsuario
INSERT INTO dbo.Especialidades SELECT NEWID(), 'FORENSE',171,GETDATE(),@idUsuario
INSERT INTO dbo.Especialidades SELECT NEWID(), 'MEDICINA DEL TRABAJO / LABORAL',172,GETDATE(),@idUsuario
INSERT INTO dbo.Especialidades SELECT NEWID(), 'MEDICINA LEGAL',173,GETDATE(),@idUsuario
INSERT INTO dbo.Especialidades SELECT NEWID(), 'NEFROLOGIA',181,GETDATE(),@idUsuario
INSERT INTO dbo.Especialidades SELECT NEWID(), 'NEFROLOGIA INFANTIL',182,GETDATE(),@idUsuario
INSERT INTO dbo.Especialidades SELECT NEWID(), 'NEUMONOLOGIA',191,GETDATE(),@idUsuario
INSERT INTO dbo.Especialidades SELECT NEWID(), 'NEUMONOLOGIA INFANTIL',192,GETDATE(),@idUsuario
INSERT INTO dbo.Especialidades SELECT NEWID(), 'NEUMOTISIOLOGIA',193,GETDATE(),@idUsuario
INSERT INTO dbo.Especialidades SELECT NEWID(), 'NEUMOTISIOLOGIA INFANTIL',194,GETDATE(),@idUsuario
INSERT INTO dbo.Especialidades SELECT NEWID(), 'NEUROCIRUGIA',201,GETDATE(),@idUsuario
INSERT INTO dbo.Especialidades SELECT NEWID(), 'NEUROFISIOLOGIA',202,GETDATE(),@idUsuario
INSERT INTO dbo.Especialidades SELECT NEWID(), 'NEUROFONIATRIA',203,GETDATE(),@idUsuario
INSERT INTO dbo.Especialidades SELECT NEWID(), 'NEUROLOGIA',204,GETDATE(),@idUsuario
INSERT INTO dbo.Especialidades SELECT NEWID(), 'NEUROLOGIA INFANTIL',205,GETDATE(),@idUsuario
INSERT INTO dbo.Especialidades SELECT NEWID(), 'DIABETES',211,GETDATE(),@idUsuario
INSERT INTO dbo.Especialidades SELECT NEWID(), 'NUTRICION',212,GETDATE(),@idUsuario
INSERT INTO dbo.Especialidades SELECT NEWID(), 'NUTRICION INFANTIL',213,GETDATE(),@idUsuario
INSERT INTO dbo.Especialidades SELECT NEWID(), 'OBESIDAD',214,GETDATE(),@idUsuario
INSERT INTO dbo.Especialidades SELECT NEWID(), 'CLINICA ESTOMATOLOGICA',223,GETDATE(),@idUsuario
INSERT INTO dbo.Especialidades SELECT NEWID(), 'OFTALMOLOGIA',231,GETDATE(),@idUsuario
INSERT INTO dbo.Especialidades SELECT NEWID(), 'OFTALMOLOGIA INFANTIL',232,GETDATE(),@idUsuario
INSERT INTO dbo.Especialidades SELECT NEWID(), 'ONCOLOGIA',241,GETDATE(),@idUsuario
INSERT INTO dbo.Especialidades SELECT NEWID(), 'ONCOLOGIA INFANTIL',242,GETDATE(),@idUsuario
INSERT INTO dbo.Especialidades SELECT NEWID(), 'OTORRINOLARINGOLOGIA',251,GETDATE(),@idUsuario
INSERT INTO dbo.Especialidades SELECT NEWID(), 'OTORRINOLARINGOLOGIA INFANTIL',252,GETDATE(),@idUsuario
INSERT INTO dbo.Especialidades SELECT NEWID(), 'ANATOMIA PATOLOGICA',261,GETDATE(),@idUsuario
INSERT INTO dbo.Especialidades SELECT NEWID(), 'CITOLOGIA',262,GETDATE(),@idUsuario
INSERT INTO dbo.Especialidades SELECT NEWID(), 'NEONATOLOGIA',271,GETDATE(),@idUsuario
INSERT INTO dbo.Especialidades SELECT NEWID(), 'PEDIATRIA',272,GETDATE(),@idUsuario
INSERT INTO dbo.Especialidades SELECT NEWID(), 'PERINATOLOGIA',273,GETDATE(),@idUsuario
INSERT INTO dbo.Especialidades SELECT NEWID(), 'NEUROPSIQUIATRIA',281,GETDATE(),@idUsuario
INSERT INTO dbo.Especialidades SELECT NEWID(), 'PSIQUIATRIA',282,GETDATE(),@idUsuario
INSERT INTO dbo.Especialidades SELECT NEWID(), 'PSIQUIATRIA INFANTO JUVENIL',283,GETDATE(),@idUsuario
INSERT INTO dbo.Especialidades SELECT NEWID(), 'DIAGNOSTICO POR IMAGENES',291,GETDATE(),@idUsuario
INSERT INTO dbo.Especialidades SELECT NEWID(), 'ECOGRAFIA',292,GETDATE(),@idUsuario
INSERT INTO dbo.Especialidades SELECT NEWID(), 'ELECTROMIOGRAFIA',293,GETDATE(),@idUsuario
INSERT INTO dbo.Especialidades SELECT NEWID(), 'MEDICINA NUCLEAR',294,GETDATE(),@idUsuario
INSERT INTO dbo.Especialidades SELECT NEWID(), 'RADIOLOGIA',295,GETDATE(),@idUsuario
INSERT INTO dbo.Especialidades SELECT NEWID(), 'RADIOTERAPIA',296,GETDATE(),@idUsuario
INSERT INTO dbo.Especialidades SELECT NEWID(), 'REUMATOLOGIA',301,GETDATE(),@idUsuario
INSERT INTO dbo.Especialidades SELECT NEWID(), 'TOXICOLOGIA',311,GETDATE(),@idUsuario
INSERT INTO dbo.Especialidades SELECT NEWID(), 'ORTOPEDIA',322,GETDATE(),@idUsuario
INSERT INTO dbo.Especialidades SELECT NEWID(), 'ORTOPEDIA INFANTIL',323,GETDATE(),@idUsuario
INSERT INTO dbo.Especialidades SELECT NEWID(), 'OSTEOLOGIA',324,GETDATE(),@idUsuario
INSERT INTO dbo.Especialidades SELECT NEWID(), 'TRAUMATOLOGIA Y ORTOPEDIA',325,GETDATE(),@idUsuario
INSERT INTO dbo.Especialidades SELECT NEWID(), 'TRAUMATOLOGIA INFANTIL',326,GETDATE(),@idUsuario
INSERT INTO dbo.Especialidades SELECT NEWID(), 'UROLOGIA',331,GETDATE(),@idUsuario
INSERT INTO dbo.Especialidades SELECT NEWID(), 'UROLOGIA INFANTIL',332,GETDATE(),@idUsuario
INSERT INTO dbo.Especialidades SELECT NEWID(), 'VARIOS / OTROS',991,GETDATE(),@idUsuario
INSERT INTO dbo.Especialidades SELECT NEWID(), 'CIRUGIA BUCOMAXILOFACIAL',221,GETDATE(),@idUsuario
INSERT INTO dbo.Especialidades SELECT NEWID(), 'ENDODONCIA',222,GETDATE(),@idUsuario
INSERT INTO dbo.Especialidades SELECT NEWID(), 'CLINICA ESTOMATOLOGICA',223,GETDATE(),@idUsuario
INSERT INTO dbo.Especialidades SELECT NEWID(), 'ODONTOLOGIA',224,GETDATE(),@idUsuario
INSERT INTO dbo.Especialidades SELECT NEWID(), 'ODONTOPEDIATRIA',225,GETDATE(),@idUsuario
INSERT INTO dbo.Especialidades SELECT NEWID(), 'ORTODONCIA',226,GETDATE(),@idUsuario
INSERT INTO dbo.Especialidades SELECT NEWID(), 'ORTOPEDIA MAXILAR',227,GETDATE(),@idUsuario
INSERT INTO dbo.Especialidades SELECT NEWID(), 'PERIODONCIA',228,GETDATE(),@idUsuario
INSERT INTO dbo.Especialidades SELECT NEWID(), 'ANATOMIA PATOLOGICA BUCALMAXILOFACIAL',229,GETDATE(),@idUsuario
INSERT INTO dbo.Especialidades SELECT NEWID(), 'TRAUMATOLOGIA MAXILO FACIAL',327,GETDATE(),@idUsuario
INSERT INTO dbo.Especialidades SELECT NEWID(), 'DIAGNOSTICO POR IMAGENES BUCOMAXILOFACIAL',341,GETDATE(),@idUsuario
INSERT INTO dbo.Especialidades SELECT NEWID(), 'PROTESIS DENTOBUCOMAXILAR',342,GETDATE(),@idUsuario
INSERT INTO dbo.Especialidades SELECT NEWID(), 'MEDICINA DEL DEPORTE',61,GETDATE(),@idUsuario
INSERT INTO dbo.Especialidades SELECT NEWID(), 'FISIATRIA (MEDICINA FISICA Y REHABILITACION)',321,GETDATE(),@idUsuario
INSERT INTO dbo.Especialidades SELECT NEWID(), 'KINESIOLOGIA GENERAL',343,GETDATE(),@idUsuario
INSERT INTO dbo.Especialidades SELECT NEWID(), 'KINESIOLOGIA EN PEDIATRIA',344,GETDATE(),@idUsuario
INSERT INTO dbo.Especialidades SELECT NEWID(), 'KINESIOLOGIA EN CARDIO RESPIRATORIO',345,GETDATE(),@idUsuario
INSERT INTO dbo.Especialidades SELECT NEWID(), 'KINESIOLOGIA EN TRAUMATOLOGIA Y ORTOPEDIA',346,GETDATE(),@idUsuario
INSERT INTO dbo.Especialidades SELECT NEWID(), 'PSICOLOGIA CLINICA',347,GETDATE(),@idUsuario
INSERT INTO dbo.Especialidades SELECT NEWID(), 'PSICOLOGIA SOCIAL Y/O COMUNITARIA',348,GETDATE(),@idUsuario
INSERT INTO dbo.Especialidades SELECT NEWID(), 'PSICOLOGIA JURIDICA Y/O FORENSE',349,GETDATE(),@idUsuario
INSERT INTO dbo.Especialidades SELECT NEWID(), 'PSICOLOGIA LABORAL Y/O DEL TRABAJO Y/O DE LAS ORGANIZACIONES',350,GETDATE(),@idUsuario
INSERT INTO dbo.Especialidades SELECT NEWID(), 'PSICOLOGIA EDUCACIONAL',351,GETDATE(),@idUsuario
INSERT INTO dbo.Especialidades SELECT NEWID(), 'PSICOLOGIA SANITARIA',352,GETDATE(),@idUsuario
INSERT INTO dbo.Especialidades SELECT NEWID(), 'NEUROPSIQUIATRIA',281,GETDATE(),@idUsuario
INSERT INTO dbo.Especialidades SELECT NEWID(), 'PSIQUIATRIA',282,GETDATE(),@idUsuario
INSERT INTO dbo.Especialidades SELECT NEWID(), 'PSIQUIATRIA INFANTO JUVENIL',283,GETDATE(),@idUsuario
INSERT INTO dbo.Especialidades SELECT NEWID(), 'BIOQUIMICA',353,GETDATE(),@idUsuario
INSERT INTO dbo.Especialidades SELECT NEWID(), 'TOXICOLOGIA',311,GETDATE(),@idUsuario
INSERT INTO dbo.Especialidades SELECT NEWID(), 'BROMATOLOGIA, NUTRICION Y TECNOLOGIA DE ALIMENTOS',354,GETDATE(),@idUsuario
INSERT INTO dbo.Especialidades SELECT NEWID(), 'BIOTECNOLOGIA',355,GETDATE(),@idUsuario
